name: Deploy AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/'
  workflow_dispatch:  # This allows manual triggering from the GitHub UI

jobs:
  deploy-lambda: # Name of the job
    runs-on: ubuntu-latest # Specifies the runner
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python # Sets up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Dependencies # Installs required packages
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt -t lambda/

      - name: Configure AWS Credentials # Sets up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1

      - name: Deploy Lambda Function # Zips the lambda directory and updates the function
        run: |
          cd lambda
          zip -r lambda.zip .
          aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file fileb://lambda.zip
